import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import joblib
import numpy as np
import pandas as pd
import streamlit as st
from src.inference import predict


st.title("Breast Cancer Detection 🧬")
st.markdown(
    "This application uses a machine learning model to predict whether a tumor is **Benign** or **Malignant** "
    "based on selected diagnostic features."
)
st.caption(
    "⚠️ This prediction is generated by a machine learning model and should not be considered a medical diagnosis."
)

st.markdown('Enter the following details:')

if 'form_id' not in st.session_state:
    st.session_state.form_id = 0

# Initialize
if 'prediction' not in st.session_state:
    st.session_state.prediction = None

if 'confidence' not in st.session_state:
    st.session_state.confidence = None

# Form
with st.form(f'breast_cancer_form_{st.session_state.form_id}'):

    st.subheader("📏 Size & Shape Features")
    worst_peri = st.text_input('Worst Perimeter', placeholder='50 - 260')
    worst_area = st.text_input("Worst Area", placeholder='200 - 4500')
    worst_rad = st.text_input('Worst Radius', placeholder='7 - 35')
    mean_radius = st.text_input('Mean Radius', placeholder='6 - 30')
    mean_area = st.text_input('Mean Area', placeholder='150 - 2500')
    area_error = st.text_input('Area Error', placeholder='5 - 550')

    st.subheader("🧪 Texture & Concavity Features")
    mean_concave = st.text_input('Mean Concave Points', placeholder='0.0 - 0.20')
    worst_concave = st.text_input('Worst Concave Points', placeholder='0.0 - 0.30')
    mean_concavity = st.text_input('Mean Concavity', placeholder='0.0 - 0.45')
    mean_peri = st.text_input('Mean Perimeter', placeholder='40 - 190')

    submitted = st.form_submit_button('Predict')

# Predict

if submitted:
    try:
        values = [
            float(worst_peri),
            float(worst_area),
            float(worst_rad),
            float(mean_concave),
            float(worst_concave),
            float(mean_peri),
            float(mean_concavity),
            float(mean_radius),
            float(mean_area),
            float(area_error)
        ]

        input_df = pd.DataFrame([values], columns = [
            'worst perimeter', 'worst area', 'worst radius', 'mean concave points',
            'worst concave points', 'mean perimeter', 'mean concavity',
            'mean radius', 'mean area', 'area error'
        ])

        pred, proba = predict(input_df)
        st.session_state.prediction = pred
        st.session_state.confidence = proba


    except ValueError:
        st.session_state.prediction = 'error'

# Output
st.markdown("---")
st.subheader("🔍 Prediction Result")

if st.session_state.prediction == 1:
    st.success(
        f"🟢 Prediction: Benign (Low Risk)\n\n"
        f"Confidence: {st.session_state.confidence[1]*100:.1f}%"
    )

elif st.session_state.prediction == 0:
    st.warning(
        f"🔴 Prediction: Malignant (High Risk)\n\n"
        f"Confidence: {st.session_state.confidence[0]*100:.1f}%"
    )

elif st.session_state.prediction == 'error':
    st.error("❌ Please enter valid numeric values")

# Clear button
if st.button('Clear'):
    st.session_state.prediction = None
    st.session_state.form_id += 1
    st.rerun()